@echo off
REM SUBST U: C:\LANG\BP\UNITS
CD SRC
SET MAINDIR=U:
SET TPUDIR=%MAINDIR%\TPRO;%MAINDIR%\OPRO;%MAINDIR%\APRO\SRC
SET TPUDIR=%TPUDIR%
SET INCDIR=%TPUDIR%
SET OBJDIR=%TPUDIR%;%MAINDIR%\OPROOBJ
BPC QMODEM -B -$O+ -$F+ -U%TPUDIR% -O%OBJDIR% -I%INCDIR% -DOVR;PRODUCTION
CD ..
